<?php

/**
 * @file
 * Deployer recipe
 */

namespace Deployer;

require 'recipe/common.php';
require 'contrib/rsync.php';

set('application', 'elaintehtaat.fi');
set('keep_releases', 3);

$host = getenv('SSH_HOST');
$port = getenv('SSH_PORT');
$user = getenv('SSH_USER');

if (!$host || !$port || !$user) {
  throw new \LogicException("Missing required environment variables");
}

host('production')
  ->setHostname($host)
  ->setPort($port)
  ->setRemoteUser($user)
  // ~/public_html is a symlink. Point the domain's
  // document root (konsoleH) at current/web.
  ->set('deploy_path', '~/public_html')
  // Keep DB dumps and temporary files outside the web-accessible tree.
  ->set('backup_path', '~/backups/elaintehtaat')
  ->set('tmp_path', '~/tmp/elaintehtaat');

// Hetzner ships one CLI binary per PHP version; match CI (PHP 8.5).
set('bin/php', '/usr/bin/php85');
set('bin/drush', '{{bin/php}} {{release_path}}/vendor/bin/drush --root={{release_path}}/web');

set('shared_dirs', [
  'web/sites/default/files',
  'private',
]);
set('shared_files', [
  'web/sites/default/settings.local.php',
]);
// PHP runs as the SSH user, so nothing needs to be made writable.
set('writable_dirs', []);

set('rsync', [
  'exclude' => [
    '/.git',
    '/.github',
    '/.idea',
    '/.editorconfig',
    '/.env',
    '/.env.example',
    '/.phpcs-cache',
    '/.phpunit.cache',
    '/compose.yaml',
    '/deploy.php',
    '/docker',
    '/Makefile',
    '/phpcs.xml*',
    '/phpstan.neon*',
    '/phpunit.xml*',
    '/private',
    '/web/sites/default/files',
    '/web/sites/default/settings.local.php',
    '/web/sites/simpletest',
    '.DS_Store',
  ],
  'exclude-file' => FALSE,
  'include' => [],
  'include-file' => FALSE,
  'filter' => [],
  'filter-file' => FALSE,
  'filter-perdir' => FALSE,
  // Recursive, symlinks, permissions, times
  'flags' => 'rlptz',
  'options' => ['delete'],
  'timeout' => 900,
]);
set('rsync_src', __DIR__);
set('rsync_dest', '{{release_path}}');

/**
 * Reads a variable from the environment of the machine running dep.
 */
function read_env(string $name, bool $required = TRUE): ?string {
  $value = getenv($name);
  if ($value === FALSE || $value === '') {
    if ($required) {
      throw error("Environment variable $name is not set.");
    }
    return NULL;
  }
  return $value;
}

/**
 * Writes a string to a file on the host with the given mode.
 */
function upload_contents(string $contents, string $destination, string $mode): void {
  $local = tempnam(sys_get_temp_dir(), 'deploy');
  file_put_contents($local, $contents);
  try {
    upload($local, $destination);
    run("chmod $mode " . escapeshellarg($destination));
  }
  finally {
    unlink($local);
  }
}

desc('Renders settings.local.php from environment variables');
task('deploy:settings', function () {
  $e = static fn(mixed $value): string => var_export($value, TRUE);

  run('mkdir -p {{tmp_path}} {{deploy_path}}/shared/web/sites/default');
  // PHP does not expand "~", so settings.local.php needs absolute paths.
  $shared = run('cd {{deploy_path}}/shared && pwd -P');
  $tmp = run('cd {{tmp_path}} && pwd -P');

  $lines = [
    '<?php',
    '',
    '// Generated by deploy.php on every deploy. Do not edit on the server;',
    '// change the GitHub "production" environment secrets instead.',
    '',
    '// --- Database ---------------------------------------------------------------',
    "\$databases['default']['default']['host'] = " . $e(read_env('DB_HOST')) . ';',
    "\$databases['default']['default']['port'] = " . $e((int) (read_env('DB_PORT', FALSE) ?? 3306)) . ';',
    "\$databases['default']['default']['database'] = " . $e(read_env('DB_NAME')) . ';',
    "\$databases['default']['default']['username'] = " . $e(read_env('DB_USERNAME')) . ';',
    "\$databases['default']['default']['password'] = " . $e(read_env('DB_PASSWORD')) . ';',
  ];
  if ($ca = read_env('DB_SSL_CA', FALSE)) {
    // Hetzner's managed database only accepts TLS with its own CA. PDO wants
    // a file path, so store the certificate next to settings.local.php.
    $caPath = "$shared/db-ca.pem";
    upload_contents($ca . "\n", $caPath, '0440');
    $lines[] = "\$databases['default']['default']['pdo'][\\Pdo\\Mysql::ATTR_SSL_CA] = " . $e($caPath) . ';';
  }

  $trusted = array_values(array_filter(array_map('trim', explode(',', read_env('TRUSTED_HOSTS')))));
  array_push($lines,
    '',
    '// --- Core settings -----------------------------------------------------------',
    "\$settings['hash_salt'] = " . $e(read_env('HASH_SALT')) . ';',
    "\$settings['trusted_host_patterns'] = " . $e($trusted) . ';',
    "\$settings['file_temp_path'] = " . $e($tmp) . ';',
    // Drupal chmods sites/default to 0555, which breaks deploy:cleanup.
    "\$settings['skip_permissions_hardening'] = TRUE;",
    '',
    '// No Varnish in front of PHP here: do not trust X-Forwarded-* headers.',
    "\$settings['reverse_proxy'] = FALSE;",
    "\$settings['omit_vary_cookie'] = FALSE;",
    '',
    '// --- Redis -------------------------------------------------------------------',
  );

  if ($redisHost = read_env('REDIS_HOST', FALSE)) {
    $lines[] = "\$settings['redis.connection']['host'] = " . $e($redisHost) . ';';
    $lines[] = "\$settings['redis.connection']['port'] = " . $e((int) (read_env('REDIS_PORT', FALSE) ?? 6379)) . ';';
    if ($redisPassword = read_env('REDIS_PASSWORD', FALSE)) {
      $lines[] = "\$settings['redis.connection']['password'] = " . $e($redisPassword) . ';';
    }
  }
  else {
    // The PHP redis extension is loaded on the server, so settings.php
    // configures Redis at host "redis". Undo that when no Redis is configured.
    array_push($lines,
      "unset(\$settings['redis.connection'], \$settings['cache']['default'], \$settings['bootstrap_container_definition']);",
      "\$settings['container_yamls'] = array_values(array_filter(",
      "  \$settings['container_yamls'],",
      "  static fn(string \$file): bool => !str_contains(\$file, 'modules/contrib/redis/'),",
      '));',
    );
  }

  $lines[] = '';
  $lines[] = '// --- File storage ------------------------------------------------------------';
  // S3 is not set up in production yet: keep public:// on the local (shared)
  // disk.
  $lines[] = "\$settings['s3fs.use_s3_for_public'] = FALSE;";

  upload_contents(implode("\n", $lines) . "\n", "$shared/web/sites/default/settings.local.php", '0440');
});

/**
 * Checks whether Drupal bootstraps against the production database.
 */
function drupal_bootstraps(): bool {
  return trim(run('{{bin/drush}} status --field=bootstrap 2>/dev/null || true')) === 'Successful';
}

desc('Dumps the database before running updates');
task('drush:backup', function () {
  if (!drupal_bootstraps()) {
    warning('Drupal does not bootstrap (first deploy?), skipping the database backup.');
    return;
  }
  run('mkdir -p {{backup_path}}');
  run('{{bin/drush}} sql:dump --gzip --result-file={{backup_path}}/pre-{{release_name}}.sql');
  // Keep the five most recent dumps.
  run('ls -1t {{backup_path}}/pre-*.sql.gz | tail -n +6 | xargs -r rm -f');
});

desc('Puts the site into maintenance mode');
task('drush:maint:on', function () {
  if (!drupal_bootstraps()) {
    warning('Drupal does not bootstrap (first deploy?), skipping maintenance mode.');
    return;
  }
  run('{{bin/drush}} maint:set 1');
  set('maintenance_mode_on', TRUE);
});

desc('Takes the site out of maintenance mode');
task('drush:maint:off', function () {
  if (!get('maintenance_mode_on', FALSE)) {
    return;
  }
  run('{{bin/drush}} maint:set 0');
  set('maintenance_mode_on', FALSE);
});

desc('Runs database updates, config import and cache rebuild');
task('drush:deploy', function () {
  run('{{bin/drush}} deploy -y');
});

desc('Deploys the site');
task('deploy', [
  'deploy:info',
  'deploy:setup',
  'deploy:lock',
  'deploy:release',
  'rsync:warmup',
  'rsync',
  'deploy:shared',
  'deploy:settings',
  'drush:backup',
  'drush:maint:on',
  'drush:deploy',
  'deploy:symlink',
  'drush:maint:off',
  'deploy:unlock',
  'deploy:cleanup',
  'deploy:success',
]);

after('deploy:failed', 'deploy:unlock');

// The database may be half-migrated, so keep the maintenance page up rather
// than let the old release run against it.
after('deploy:failed', function () {
  if (get('maintenance_mode_on', FALSE)) {
    warning('The site is still in maintenance mode. Restore {{backup_path}}/pre-{{release_name}}.sql.gz or fix and redeploy, then run: {{bin/drush}} maint:set 0');
  }
});
