<?php

declare(strict_types=1);

namespace Drupal\elaintehtaat\Hook;

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Hook\Attribute\Hook;
use Drupal\node\NodeInterface;
use Drupal\path_alias\PathAliasInterface;
use Drupal\pathauto\PathautoGeneratorInterface;

/**
 * Keeps album URL aliases in sync with their parent project.
 *
 * Album aliases follow the pattern /<project alias>/<album title>. Pathauto
 * only regenerates an alias when the aliased entity itself is saved, so when
 * a project's alias changes its albums would keep stale aliases. Every change
 * to a project alias, whether generated by pathauto, edited on the node form
 * or edited in the URL alias admin UI, is a path_alias entity save, so that is
 * the event to react to.
 */
readonly class AlbumAliasHooks {

  public function __construct(
    protected EntityTypeManagerInterface $entityTypeManager,
    protected PathautoGeneratorInterface $pathautoGenerator,
  ) {}

  /**
   * Implements hook_ENTITY_TYPE_insert() for path_alias entities.
   */
  #[Hook('path_alias_insert')]
  public function pathAliasInsert(PathAliasInterface $path_alias): void {
    $this->updateAlbumAliases($path_alias);
  }

  /**
   * Implements hook_ENTITY_TYPE_update() for path_alias entities.
   */
  #[Hook('path_alias_update')]
  public function pathAliasUpdate(PathAliasInterface $path_alias): void {
    $this->updateAlbumAliases($path_alias);
  }

  /**
   * Regenerates the aliases of all albums belonging to the aliased project.
   */
  protected function updateAlbumAliases(PathAliasInterface $path_alias): void {
    if (!preg_match('#^/node/(\d+)$#', $path_alias->getPath(), $matches)) {
      return;
    }

    $storage = $this->entityTypeManager->getStorage('node');
    $project = $storage->load($matches[1]);
    if (!$project instanceof NodeInterface || $project->bundle() !== 'project') {
      return;
    }

    $album_ids = $storage->getQuery()
      ->accessCheck(FALSE)
      ->condition('type', 'album')
      ->condition('field_project', $project->id())
      ->execute();
    if (!$album_ids) {
      return;
    }

    foreach ($storage->loadMultiple($album_ids) as $album) {
      foreach (array_keys($album->getTranslationLanguages()) as $langcode) {
        $this->pathautoGenerator->updateEntityAlias($album->getTranslation($langcode), 'update');
      }
      // The album itself is not saved, so rendered pages that link to it or
      // its media pages (see MediaPageController) would keep the old alias.
      Cache::invalidateTags($album->getCacheTagsToInvalidate());
    }
  }

}
